name: Greeeter bot
on:
  issue_comment:
    types: [created]
jobs:
  bot:
    if: startsWith(github.event.comment.body, '/greet')
    runs-on: self-hosted
    steps:
    - name: React
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.reactions.createForIssueComment({
            owner: context.repo.owner, repo: context.repo.repo,
            comment_id: context.payload.comment.id, content: "rocket"
          })
